In [2]:
import numpy as np 
import SBP as sb 
import matplotlib.pyplot as plt 
import sympy as sp # For symbolic operations 


The paper used in this homework is the paper titled 
"
Entropy stable h/p-nonconforming discretization with the
summation-by-parts property for the compressible Euler and
Navier–Stokes equations
"

## Derivation of Equation (39) from Equation (38)

### Step 1: Start from Equation (38)
Equation (38) is given by:

$$
\frac{du}{dt} + \frac{1}{3} D_{x_1} \text{diag}(u) u + \frac{1}{3} \text{diag}(u) D_{x_1} u = D_{x_1} \Theta, \quad \Theta \equiv D_{x_1} u.
$$

We want to derive the **energy estimate** by multiplying both sides by $ u^T P $, where $ P $ is the diagonal norm matrix in the Summation-By-Parts (SBP) framework.

---

### Step 2: Multiply by $ u^T P $
Taking the inner product with $ u^T P $:

$$
 u^T P \frac{du}{dt} + \frac{1}{3} u^T P D_{x_1} \text{diag}(u) u + \frac{1}{3} u^T P \text{diag}(u) D_{x_1} u = u^T P D_{x_1} \Theta.
$$

Using the quadratic form differentiation identity:

$$
 u^T P \frac{du}{dt} = \frac{1}{2} \frac{d}{dt} u^T P u.
$$

---

### Step 3: SBP Property for $ D_{x_1} $
We use the **SBP decomposition**:

$$
 P D_{x_1} = S + \frac{1}{2} E_{x_1},
$$

where:
- $ S $ is skew-symmetric: $ S^T = -S $.
- $ E_{x_1} $ is the boundary extraction matrix.

Applying this to the **convective terms**:

$$
 u^T P D_{x_1} \text{diag}(u) u = u^T (S + \frac{1}{2} E_{x_1}) \text{diag}(u) u.
$$

Since $ S $ is skew-symmetric, we show:

$$
 u^T S \text{diag}(u) u = - (\text{diag}(u) u)^T S u = 0.
$$
### Note: 
For a scalar quantity, the transpose operator is equivilant to multipying by one, which leads to a scalar equaling the negative of it self. 
$$a = -a$$
This can only be satisfied by the zero element. Thus, the only surviving term is:

$$
 \frac{1}{3} u^T E_{x_1} \text{diag}(u) u = \frac{1}{3} (u^3(N) - u^3(1)).
$$

---

### Step 4: Viscous Term Analysis
For the viscous term:

$$
 u^T P D_{x_1} D_{x_1} u.
$$

Using SBP:

$$
 u^T P D_{x_1} D_{x_1} u = u^T S D_{x_1} u + \frac{1}{2} u^T E_{x_1} D_{x_1} u.
$$

Since $ S $ is skew-symmetric, **this term vanishes**:

$$
 u^T S D_{x_1} u = 0.
$$

Leaving us with:

$$
 u^T P D_{x_1} D_{x_1} u = u^T E_{x_1} D_{x_1} u - u^T D_{x_1}^T P D_{x_1} u.
$$

---

### Step 5: Final Energy Estimate
Combining all terms, we obtain **Equation (39):**

$$
\frac{1}{2} \frac{d}{dt} u^T P u + \frac{1}{3} (u^3(N) - u^3(1)) = u^T E_{x_1} D_{x_1} u - u^T D_{x_1}^T P D_{x_1} u.
$$



## Forming the 2-Point flux

In [55]:
'''
Forming the matricies and the 2-point flux function. 
Using the same values as the paper discussed. 
'''

n = 2
u = sp.symbols(f'u1:{n+2}')
D = sb.dlagrange(n)
print("The matrix D \n", D)

F = sp.zeros(n+1,n+1)
for j in range(n+1): 
    for i in range(n+1): 
        F[i,j] = sp.Rational(1,6)*(u[i]**2 + u[i]*u[j] + u[j]**2)
print("and the 2-point entropy flux function is \n")
sp.simplify(F)

The matrix D 
 [[-1.5  2.  -0.5]
 [-0.5  0.   0.5]
 [ 0.5 -2.   1.5]]
and the 2-point entropy flux function is 



Matrix([
[                    u1**2/2, u1**2/6 + u1*u2/6 + u2**2/6, u1**2/6 + u1*u3/6 + u3**2/6],
[u1**2/6 + u1*u2/6 + u2**2/6,                     u2**2/2, u2**2/6 + u2*u3/6 + u3**2/6],
[u1**2/6 + u1*u3/6 + u3**2/6, u2**2/6 + u2*u3/6 + u3**2/6,                     u3**2/2]])

In [65]:
sp.nsimplify(np.multiply(D,F))

[[-3*u1**2/4, u1**2/3 + u1*u2/3 + u2**2/3, -u1**2/12 - u1*u3/12 - u3**2/12], [-u1**2/12 - u1*u2/12 - u2**2/12, 0, u2**2/12 + u2*u3/12 + u3**2/12], [u1**2/12 + u1*u3/12 + u3**2/12, -u2**2/3 - u2*u3/3 - u3**2/3, 3*u3**2/4]]